### ISSUE TITLE
container restarts every 5 minutes

### ISSUE THREAD

**Issue by Obliterous** [mvanduijker/viewtube-all-in-one#2]
healthcheck fails and container restarts every 5 minutes; no errors logged.

**Comment by Obliterous** [comment]
this is what I'm getting if I use interactive mode and start it manually:

296:M 28 May 2024 19:36:00.044 * Ready to accept connections
[ViewTube] Info 5/28/2024, 7:36:02 PM Starting with single node
[ViewTube] Info 5/28/2024, 7:36:02 PM Loaded configuration from /data/config.json
[ViewTube] Info 5/28/2024, 7:40:56 PM [NestFactory] Starting Nest application...
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] MongooseModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] JwtModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] ConfigHostModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] NuxtModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] DiscoveryModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] RouterModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] AppModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] ConfigModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] ConfigModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] ConfigModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] BullModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] ScheduleModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] BullModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] ProxyModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] BullModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] CacheModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] AutocompleteModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] SearchModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] CommentsModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] PlaylistsModule dependencies initialized
[ViewTube] Info 5/28/2024, 7:40:56 PM [InstanceLoader] HomepageModule dependencies initialized
[ViewTube] Error        5/28/2024, 7:40:56 PM [MongooseModule] Unable to connect to the database. Retrying (1)... - {"stack":[""]}
[ViewTube] Error        5/28/2024, 7:40:56 PM [MongooseModule] Unable to connect to the database. Retrying (2)... - {"stack":[""]}
[ViewTube] Error        5/28/2024, 7:40:56 PM [MongooseModule] Unable to connect to the database. Retrying (3)... - {"stack":[""]}
[ViewTube] Error        5/28/2024, 7:40:56 PM [MongooseModule] Unable to connect to the database. Retrying (4)... - {"stack":[""]}
[ViewTube] Error        5/28/2024, 7:40:56 PM [MongooseModule] Unable to connect to the database. Retrying (5)... - {"stack":[""]}
[ViewTube] Error        5/28/2024, 7:40:56 PM [MongooseModule] Unable to connect to the database. Retrying (6)... - {"stack":[""]}
[ViewTube] Error        5/28/2024, 7:40:56 PM [MongooseModule] Unable to connect to the database. Retrying (7)... - {"stack":[""]}
[ViewTube] Error        5/28/2024, 7:40:56 PM [MongooseModule] Unable to connect to the database. Retrying (8)... - {"stack":[""]}
[ViewTube] Error        5/28/2024, 7:40:56 PM [MongooseModule] Unable to connect to the database. Retrying (9)... - {"stack":[""]}
[ViewTube] Error        5/28/2024, 7:40:56 PM [ExceptionHandler] connect ECONNREFUSED 127.0.0.1:27017 - {"stack":["MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017\n    at _handleConnectionErrors (/home/app/node_modules/.pnpm/mongoose@7.6.10/node_modules/mongoose/lib/connection.js:809:11)\n    at NativeConnection.asPromise (/home/app/node_modules/.pnpm/mongoose@7.6.10/node_modules/mongoose/lib/connection.js:1271:11)\n    at async /home/app/node_modules/.pnpm/@nestjs+mongoose@10.0.4_@nestjs+common@10.3.3_@nestjs+core@10.3.3_mongoose@7.6.10_rxjs@7.8.1/node_modules/@nestjs/mongoose/dist/mongoose-core.module.js:62:112"]}
1296:signal-handler (1716925256) Received SIGTERM scheduling shutdown...
root@8ffc4350cf08:/home/app# 1296:M 28 May 2024 19:40:56.587 # User requested shutdown...
1296:M 28 May 2024 19:40:56.587 # Redis is now ready to exit, bye bye...

**Comment by mvanduijker** [comment]
with which command do you run the container? I don't seen any mongodb logs in your output.

**Comment by mvanduijker** [comment]
can you check if you run against this [issue](https://github.com/mvanduijker/viewtube-all-in-one/issues/1)?
